/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import config.TablePrinter;
import config.dbconnector;
import config.excelExport;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
import user.user_dash;

/**
 *
 * @author entac
 */
public final class records extends javax.swing.JFrame {

    /**
     * Creates new form records
     */
    public records() {
        initComponents();
        tb();
    }
    
    dbconnector db = new dbconnector();
    public String action;
    
    public void tb(){
        try{
 
       ResultSet res = db.getData("SELECT \n" +
                                        "rec.id AS 'ID',\n" +
                                        "rec.date AS 'Date',\n" +
                                        "COALESCE(stud.s_tag, s.tag) AS 'Tag',\n" +
                                        "COALESCE(stud.s_name, s.name) AS 'Name',\n" +
                                        "COALESCE(stud.s_mi, s.mid) AS 'Middle Name',\n" +
                                        "COALESCE(stud.s_last, s.last) AS 'Last Name',\n" +
                                        "COALESCE(grd.lvl, s.pos_type) AS 'Pos/Course',\n" +
                                        "rec.time_in AS 'Time In',\n" +
                                        "rec.time_out AS 'Time Out',\n" +
                                        "COALESCE(stud.s_identification,identification) AS 'Type' \n"+
                                        "FROM tbl_records rec\n" +
                                        "LEFT JOIN tbl_students stud ON rec.student_id = stud.s_id\n" +
                                        "LEFT JOIN tbl_gradelvl grd ON grd.num = stud.s_gradesec\n" +
                                        "LEFT JOIN tbl_stake s ON rec.stake_id = s.id;");

        rec_list.setModel(DbUtils.resultSetToTableModel(res));
        }catch(SQLException e){
            System.out.println(""+e.getLocalizedMessage());
        }
        
        
    }
    
  
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        type = new javax.swing.JComboBox<>();
        txtsearch = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        rec_list = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel1.setText("Records");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jLabel2.setText("[BACK]");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, -1, -1));

        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Type", "Student", "Staff" }));
        type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeActionPerformed(evt);
            }
        });
        jPanel1.add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 100, 30));

        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });
        jPanel1.add(txtsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 200, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PIC/search.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 30, 20));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PIC/kilid.jpg"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -10, -1, 110));

        jLabel10.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel10.setText("Print Table");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, -1, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel9.setText("Export To Excel");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 80, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel11.setText("Any Key or TAG#");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, 20));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setViewportView(rec_list);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(945, 499));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed

    }//GEN-LAST:event_txtsearchActionPerformed

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
        try{ 
         String s = txtsearch.getText();
        ResultSet res = db.getData("SELECT \n" +
                                        "rec.id AS 'ID',\n" +
                                        "rec.date AS 'Date',\n" +
                                        "COALESCE(stud.s_tag, s.tag) AS 'Tag',\n" +
                                        "COALESCE(stud.s_name, s.name) AS 'Name',\n" +
                                        "COALESCE(stud.s_mi, s.mid) AS 'Middle Name',\n" +
                                        "COALESCE(stud.s_last, s.last) AS 'Last Name',\n" +
                                        "COALESCE(grd.lvl, s.pos_type) AS 'Pos/Course',\n" +
                                        "rec.time_in AS 'Time In',\n" +
                                        "rec.time_out AS 'Time Out',\n" +
                                        "COALESCE(stud.s_identification,identification) AS Type \n"+
                                        "FROM tbl_records rec\n" +
                                        "LEFT JOIN tbl_students stud ON rec.student_id = stud.s_id\n" +
                                        "LEFT JOIN tbl_gradelvl grd ON grd.num = stud.s_gradesec\n" +
                                        "LEFT JOIN tbl_stake s ON rec.stake_id = s.id "
                                        + "WHERE stud.s_name LIKE '%"+s+"%' OR stud.s_last LIKE '%"+s+"%' OR stud.s_name LIKE '%"+s+"%' OR stud.s_tag LIKE '%"+s+"%'"
                                        + "OR s.name LIKE '%"+s+"%' OR s.last LIKE '%"+s+"%' OR s.tag LIKE '%"+s+"%' ");
        
       DefaultTableModel model = (DefaultTableModel) rec_list.getModel();
        model.setRowCount(0); 
      
         while (res.next()) {

            String id = String.valueOf(res.getString("ID"));
            String date = res.getString("Date");
            String tag = res.getString("Tag");
            String last = res.getString("Last Name");
            String mid = res.getString("Middle Name");
            String first = res.getString("Name");
            String grd = res.getString("Pos/Course");
            String typ = res.getString("Type");
            String ot = res.getString("Time Out");
            String in = res.getString("Time In");
          

            String table[] = {id,tag,date,first,mid,last,grd,in,ot,typ};

            DefaultTableModel tblmod = (DefaultTableModel)rec_list.getModel();
            tblmod.addRow(table);

        }
     
       
        } catch (SQLException ex) {
            Logger.getLogger(records.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtsearchKeyReleased

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        switch(action){
            case "admin":
                Dash op = new Dash();
                op.setVisible(true);
                this.dispose();
                break;
            case "user":
                user_dash us = new user_dash();
                us.setVisible(true);
                this.dispose();
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
       excelExport ex = new excelExport();
      ex.export((DefaultTableModel)rec_list.getModel());
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
    TablePrinter tbl = new TablePrinter((JTable) rec_list,"Attendance Records" );
    tbl.print();
      
    }//GEN-LAST:event_jLabel10MouseClicked

    private void typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionPerformed
        try {
     String t = "";
     if(type.getSelectedItem().equals("Staff")){
         t = "stake";
     }else if(type.getSelectedItem().equals("Student")){
         t = "student";
     }
          
       ResultSet res = db.getData("SELECT \n" +
                                        "rec.id AS 'ID',\n" +
                                        "rec.date AS 'Date',\n" +
                                        "COALESCE(stud.s_tag, s.tag) AS 'Tag',\n" +
                                        "COALESCE(stud.s_name, s.name) AS 'Name',\n" +
                                        "COALESCE(stud.s_mi, s.mid) AS 'Middle Name',\n" +
                                        "COALESCE(stud.s_last, s.last) AS 'Last Name',\n" +
                                        "COALESCE(grd.lvl, s.pos_type) AS 'Pos/Course',\n" +
                                        "rec.time_in AS 'Time In',\n" +
                                        "rec.time_out AS 'Time Out',\n" +
                                        "COALESCE(stud.s_identification,identification) AS Type \n"+
                                        "FROM tbl_records rec\n" +
                                        "LEFT JOIN tbl_students stud ON rec.student_id = stud.s_id\n" +
                                        "LEFT JOIN tbl_gradelvl grd ON grd.num = stud.s_gradesec\n" +
                                        "LEFT JOIN tbl_stake s ON rec.stake_id = s.id "
                                        + "WHERE s.identification = '"+t+"' OR stud.s_identification = '"+t+"'");
        
       DefaultTableModel model = (DefaultTableModel) rec_list.getModel();
        model.setRowCount(0); 
      
         while (res.next()) {

            String id = String.valueOf(res.getString("ID"));
            String date = res.getString("Date");
            String tag = res.getString("Tag");
            String last = res.getString("Last Name");
            String mid = res.getString("Middle Name");
            String first = res.getString("Name");
            String grd = res.getString("Pos/Course");
            String typ = res.getString("Type");
            String ot = res.getString("Time Out");
            String in = res.getString("Time In");
          

            String table[] = {id,tag,date,first,mid,last,grd,in,ot,typ};

            DefaultTableModel tblmod = (DefaultTableModel)rec_list.getModel();
            tblmod.addRow(table);

        }
       if (type.getSelectedItem().equals("All Type")){
     
       model.setRowCount(0); 
       tb();
     }

       
       
        } catch (SQLException ex) {
            Logger.getLogger(records.class.getName()).log(Level.SEVERE, null, ex);
        }
     
    }//GEN-LAST:event_typeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(records.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(records.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(records.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(records.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new records().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable rec_list;
    private javax.swing.JTextField txtsearch;
    private javax.swing.JComboBox<String> type;
    // End of variables declaration//GEN-END:variables
}
