/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import static Students.newstud.getHeightFromWidth;
import com.toedter.calendar.JTextFieldDateEditor;
import config.dbconnector;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import user.user_dash;

/**
 *
 * @author entac
 */
public class update extends javax.swing.JFrame {

    /**
     * Creates new form update
     */
    public update() {
        initComponents();
    }
    
    public String destination = "";
    File selectedFile;
   
    public String oldpath;
    public String path;
    
    public String gender; 
    public String action;
    
     public int existcheck(String path){
        File file = new File(path);
        String filename = file.getName();
        
        Path filePath = Paths.get("src/stakepic", filename);
        boolean fileExist = Files.exists(filePath);
        
        if(fileExist){
            return 1;
        }else{
            return 0;
        }
    }
    
  
       public static int getHeightFromWidth(String imagePath, int desiredWidth) {
        try {
            // Read the image file
            File imageFile = new File(imagePath);
            BufferedImage image = ImageIO.read(imageFile);
            
            // Get the original width and height of the image
            int originalWidth = image.getWidth();
            int originalHeight = image.getHeight();
            
            // Calculate the new height based on the desired width and the aspect ratio
            int newHeight = (int) ((double) desiredWidth / originalWidth * originalHeight);
            
            return newHeight;
        } catch (IOException ex) {
            System.out.println("No image found!");
        }
        
        return -1;
    }

        public ImageIcon ResizeImage(String ImagePath, byte[] pic, JLabel label) {
            ImageIcon MyImage = null;
            if (ImagePath != null) {
                MyImage = new ImageIcon(ImagePath);
            } else {
                MyImage = new ImageIcon(pic);
            }

            if (label.getWidth() == 0) {
                return MyImage;
            }

            int newHeight = getHeightFromWidth(ImagePath, label.getWidth());
            Image img = MyImage.getImage();
            Image newImg = img.getScaledInstance(label.getWidth(), newHeight, Image.SCALE_SMOOTH);
            return new ImageIcon(newImg);
        }
            
        public void imageUpdater(String existingFilePath, String newFilePath){
               File existingFile = new File(existingFilePath);
               if (existingFile.exists()) {
                   String parentDirectory = existingFile.getParent();
                   File newFile = new File(newFilePath);
                   String newFileName = newFile.getName();
                   File updatedFile = new File(parentDirectory, newFileName);
                   existingFile.delete();
                   try {
                       Files.copy(newFile.toPath(), updatedFile.toPath(), StandardCopyOption.REPLACE_EXISTING);
                       System.out.println("Image updated successfully.");
                   } catch (IOException e) {
                       System.out.println("Error occurred while updating the image: "+e);
                   }
               } else {
                   try{
                       Files.copy(selectedFile.toPath(), new File(destination).toPath(), StandardCopyOption.REPLACE_EXISTING);
                   }catch(IOException e){
                       System.out.println("Error on update!");
                   }
               }
          }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        idno = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtmid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtlast = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtadd = new javax.swing.JTextField();
        lblchange = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txttag = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        female = new javax.swing.JRadioButton();
        male = new javax.swing.JRadioButton();
        lblpic = new javax.swing.JLabel();
        txtbday = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        browser = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        idno.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        idno.setText("0");
        jPanel1.add(idno, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 80, -1));

        jLabel2.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        jLabel2.setText("M.I");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));
        jPanel1.add(txtmid, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 230, 30));

        jLabel3.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        jLabel3.setText("Last Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));
        jPanel1.add(txtlast, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 230, 30));

        jLabel4.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        jLabel4.setText("Date of Birth");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        jLabel5.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        jLabel5.setText("Gender");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));
        jPanel1.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 230, 30));

        jLabel7.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        jLabel7.setText("Address");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));
        jPanel1.add(txtadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 230, 30));

        lblchange.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        lblchange.setText("Change Password");
        lblchange.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblchangeMouseClicked(evt);
            }
        });
        jPanel1.add(lblchange, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, -1, -1));
        jPanel1.add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 230, 30));

        jLabel10.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        jLabel10.setText("Tag#");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));
        jPanel1.add(txttag, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 230, 30));

        jLabel11.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        jLabel11.setText("Name");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));
        jPanel1.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 230, 30));

        jLabel12.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel12.setText("UPDATE");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel13.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jLabel13.setText("ID no.");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jLabel14.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        jLabel14.setText("Email");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));

        female.setText("Female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        jPanel1.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, -1));

        male.setText("Male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        jPanel1.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));

        lblpic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        jPanel1.add(lblpic, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 170, 140));

        txtbday.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(txtbday, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 230, 30));

        jButton1.setText("Remove");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 90, 30));

        jButton2.setText("Cancel");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 90, 30));

        browser.setText("Browse");
        browser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                browserMouseClicked(evt);
            }
        });
        jPanel1.add(browser, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, 90, 30));

        jButton4.setText("Update");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 90, 30));

        jLabel15.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        jLabel15.setText("Username");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(749, 531));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
         male.setSelected(false);
      
      if(female.isSelected()){
          gender = "Female";
      }else{
          gender = null;
      }
    }//GEN-LAST:event_femaleActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
       female.setSelected(false);
      
      if(male.isSelected()){
          gender = "Male";
      }else{
          gender = null;
      }
    }//GEN-LAST:event_maleActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
       switch (action){
          
           case "dash":
                Dash op = new Dash();
                
                op.setVisible(true);
                this.dispose();
               break;
           
           case "user":
               user_dash p = new user_dash();
               
               p.setVisible(true);
               this.dispose();
               
               break;
               
       }
    }//GEN-LAST:event_jButton2MouseClicked

    private void browserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_browserMouseClicked
        JFileChooser fileChooser = new JFileChooser();
                int returnValue = fileChooser.showOpenDialog(null);
                if (returnValue == JFileChooser.APPROVE_OPTION) {
                    try {
                        selectedFile = fileChooser.getSelectedFile();
                        destination = "src/stakepic/" + selectedFile.getName();
                        path  = selectedFile.getAbsolutePath();
                        
                        
                        if(existcheck(path) == 1){
                          JOptionPane.showMessageDialog(null, "File Already Exist, Rename or Choose another!");
                            destination = "";
                            path="";
                        }else{
                            lblpic.setIcon(ResizeImage(path, null, lblpic));
                            browser.setEnabled(true);
                            
                            
                        }
                    } catch (HeadlessException ex) {
                        System.out.println("File Error!");
                    }
                }
    }//GEN-LAST:event_browserMouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
       dbconnector db = new dbconnector();
      
       String bday = ((JTextFieldDateEditor)txtbday.getDateEditor()).getText();
       
       db.update("UPDATE tbl_stake  SET tag ='"+txttag.getText()+"',name='"+txtname.getText()+"',mid='"+txtmid.getText()+"',"
               + "last='"+txtlast.getText()+"',email='"+txtemail.getText()+"',bod='"+bday+"',gender='"+gender+"',address='"+txtadd.getText()+"',"
                + "user='"+txtuser.getText()+"',pic='"+destination+"' WHERE id = '"+idno.getText()+"' ");
       
            if(destination.isEmpty()){
                    File existing = new File(oldpath);
                    if(existing.exists()){
                        existing.delete();
                    }
                }else{
                    if(!(oldpath.equals(path))){
                        imageUpdater(oldpath,path);
                    }
                }
            
            
       
       
    }//GEN-LAST:event_jButton4MouseClicked

    private void lblchangeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblchangeMouseClicked
  
    changepass cp = new changepass();

    cp.setVisible(true);
    
               
    }//GEN-LAST:event_lblchangeMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       lblpic.setIcon(null);
       destination = "";
       path = "";
    }//GEN-LAST:event_jButton1MouseClicked
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browser;
    private javax.swing.JRadioButton female;
    public javax.swing.JLabel idno;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lblchange;
    public javax.swing.JLabel lblpic;
    private javax.swing.JRadioButton male;
    public javax.swing.JTextField txtadd;
    public com.toedter.calendar.JDateChooser txtbday;
    public javax.swing.JTextField txtemail;
    public javax.swing.JTextField txtlast;
    public javax.swing.JTextField txtmid;
    public javax.swing.JTextField txtname;
    public javax.swing.JTextField txttag;
    public javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
